### ISSUE TITLE
travis ci build failed because postgres services

### ISSUE THREAD

**Issue by sodrooome** [saintfactory/backend-cetak#2]
**Problem**

It looks like `postgresql` can't working on travis ci for automated testing

**What you expected**

postgres can run remotely outside our localhost or virtual machine

**Solution**

- Adding travis ci parameter and job for build postgres services
- Changing port and listen addresses in postgres services

**Possible future**

if we are going to use postgres on a production scale, it possibly the database connections will not working out (still refused), even though locally it's  functioning properly

**Comment by rblcoder** [comment]
Hi @sodrooome , two tests are failing:
```

FAIL: test_get_unauthorized_order (backend-cetak.test.test_api_urls.ProductListTestCase)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/rblcoder/backend-cetak/test/test_api_urls.py", line 35, in test_get_unauthorized_order

    self.assertEqual(response.status_code, status.HTTP_401_UNAUTHORIZED)

AssertionError: 403 != 401

======================================================================

FAIL: test_get_unauthorized_order_summary (backend-cetak.test.test_api_urls.ProductListTestCase)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/rblcoder/backend-cetak/test/test_api_urls.py", line 25, in test_get_unauthorized_order_summary

    self.assertEqual(response.status_code, status.HTTP_401_UNAUTHORIZED)

AssertionError: 403 != 401
```
